#include "FactoryPresets.h"

namespace dida { namespace factory {

static const char* kPreset_Chicago_Drill_Sub = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0.05,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Chicago Drill Sub","category":"Bass","tags":["drill","sub","808","dark"],"description":"Deep 808-style sub bass with analog warmth","oscA":{"waveform":"sine","level":0.9,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"saw","level":0.15,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":true,"level":0.7,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":200,"resonance":0.3,"drive":0.2,"envAmount":0.3,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.8,"sustain":0.4,"release":0.4},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"0737e741bd05237e"})DIDA";
static const char* kPreset_Choir_Lead = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Choir Lead","category":"Lead","tags":["choir","vocal","lush"],"description":"Vocal-like choir lead","oscA":{"waveform":"saw","level":0.5,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":4,"unisonDetune":0.25,"unisonSpread":0.5},"oscB":{"waveform":"saw","level":0.5,"detuneCents":7,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"BP","cutoff":2500,"resonance":0.6,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.1,"decay":0.3,"sustain":0.8,"release":0.8},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.5,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.35,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"f0fade41123732c5"})DIDA";
static const char* kPreset_Cinematic_Hybrid_Hit = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Cinematic Hybrid Hit","category":"FX","tags":["cinematic","hit","impact"],"description":"Massive cinematic impact hit","oscA":{"waveform":"saw","level":0.7,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":6,"unisonDetune":0.5,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.8,"detuneCents":0,"octave":-2,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0.3},"filter1":{"type":"LP24","cutoff":5000,"resonance":0.3,"drive":0.4,"envAmount":0.8,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":1.5,"sustain":0,"release":2.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.6,"reverbSize":0.9,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0.2,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"a2c704072849e37b"})DIDA";
static const char* kPreset_Crystal_Pluck = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Crystal Pluck","category":"Pluck","tags":["crystal","bright","sparkle"],"description":"Bright crystalline pluck","oscA":{"waveform":"sine","level":0.5,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"triangle","level":0.5,"detuneCents":0,"octave":2,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":12000,"resonance":0.2,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.3,"sustain":0,"release":0.6},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0.2,"delayTime":0.25,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.2,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"394512f77c187022"})DIDA";
static const char* kPreset_Dark_Air_Pad = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dark Air Pad","category":"Pad","tags":["dark","air","ambient"],"description":"Dark atmospheric pad with noise","oscA":{"waveform":"saw","level":0.4,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"triangle","level":0.3,"detuneCents":0,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0.15},"filter1":{"type":"LP24","cutoff":1500,"resonance":0.2,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":1.5,"decay":2.0,"sustain":0.6,"release":4.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.7,"reverbSize":0.9,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"79eeaa1bb1a8b430"})DIDA";
static const char* kPreset_Dark_FM_Bass = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"fm2op","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dark FM Bass","category":"Bass","tags":["fm","dark","growl"],"description":"Aggressive FM bass with metallic edge","oscA":{"waveform":"sine","level":0.8,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.6,"detuneCents":0,"octave":0,"semitone":7,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":1200,"resonance":0.4,"drive":0.3,"envAmount":0.5,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.4,"sustain":0.5,"release":0.3},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"d989db06d5bc65be"})DIDA";
static const char* kPreset_Dark_Music_Box = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dark Music Box","category":"Keys","tags":["musicbox","dark","delicate"],"description":"Haunting music box timbre","oscA":{"waveform":"triangle","level":0.6,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.3,"detuneCents":0,"octave":1,"semitone":12,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":4000,"resonance":0.15,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.8,"sustain":0,"release":1.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.3,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"c4c0b24602606035"})DIDA";
static const char* kPreset_Dark_Stringer = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dark Stringer","category":"Strings","tags":["strings","dark","cinematic"],"description":"Dark cinematic string ensemble","oscA":{"waveform":"saw","level":0.5,"detuneCents":5,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":4,"unisonDetune":0.2,"unisonSpread":0.6},"oscB":{"waveform":"saw","level":0.5,"detuneCents":-5,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":2500,"resonance":0.15,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.5,"decay":0.8,"sustain":0.8,"release":2.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.3,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.4,"reverbSize":0.6,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"98150da6951891c1"})DIDA";
static const char* kPreset_Digital_Cry_Lead = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":8,"glideTime":0.05,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Digital Cry Lead","category":"Lead","tags":["digital","cry","expressive"],"description":"Expressive digital lead with movement","oscA":{"waveform":"saw","level":0.6,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"square","level":0.4,"detuneCents":3,"octave":0,"semitone":0,"pulseWidth":0.3,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":3000,"resonance":0.5,"drive":0,"envAmount":0.6,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.3,"sustain":0.7,"release":0.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":4.0,"shape":"sine","sync":false,"depth":0.3},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[{"source":"lfo1","destination":"filter1Cutoff","amount":0.4,"bipolar":true}],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"d2c5f4b6ef8ab814"})DIDA";
static const char* kPreset_Dirty_Reese = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0.08,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dirty Reese","category":"Bass","tags":["reese","dnb","dark"],"description":"Classic detuned reese bass","oscA":{"waveform":"saw","level":0.7,"detuneCents":12,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":2,"unisonDetune":0.4,"unisonSpread":0.5},"oscB":{"waveform":"saw","level":0.7,"detuneCents":-12,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":2000,"resonance":0.5,"drive":0.4,"envAmount":0.3,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.3,"sustain":0.7,"release":0.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0.3,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"81e35e310378d366"})DIDA";
static const char* kPreset_Dream_Bell = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"fm2op","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Dream Bell","category":"Keys","tags":["bell","ethereal","soft"],"description":"Soft FM bell with long tail","oscA":{"waveform":"sine","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.5,"detuneCents":0,"octave":0,"semitone":7,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":8000,"resonance":0.2,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":2.0,"sustain":0,"release":3.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.4,"reverbSize":0.7,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"4f00de176d4130f8"})DIDA";
static const char* kPreset_Ethereal_Pad = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Ethereal Pad","category":"Pad","tags":["ethereal","ambient","dreamy"],"description":"Lush dreamy pad","oscA":{"waveform":"saw","level":0.5,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":4,"unisonDetune":0.3,"unisonSpread":0.7},"oscB":{"waveform":"triangle","level":0.4,"detuneCents":5,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":3000,"resonance":0.2,"drive":0,"envAmount":0.2,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":1.0,"decay":1.0,"sustain":0.8,"release":3.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.5,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.6,"reverbSize":0.8,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"e1df78ed6ac8140a"})DIDA";
static const char* kPreset_Evil_Square_Lead = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Evil Square Lead","category":"Lead","tags":["square","evil","aggressive"],"description":"Hard square wave lead","oscA":{"waveform":"square","level":0.8,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.35,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"square","level":0.4,"detuneCents":7,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":4000,"resonance":0.5,"drive":0.2,"envAmount":0.4,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.3,"sustain":0.7,"release":0.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0.25,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"776cf2805b021783"})DIDA";
static const char* kPreset_FM_Marimba = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"fm2op","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"FM Marimba","category":"Pluck","tags":["fm","marimba","mallet"],"description":"FM-style marimba","oscA":{"waveform":"sine","level":0.8,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.6,"detuneCents":0,"octave":0,"semitone":12,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":8000,"resonance":0.2,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.5,"sustain":0,"release":1.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.15,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"6beb19c3ee3d3e7f"})DIDA";
static const char* kPreset_Frozen_Choir = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Frozen Choir","category":"Pad","tags":["choir","frozen","icy"],"description":"Frozen choral texture","oscA":{"waveform":"saw","level":0.4,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":6,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"saw","level":0.4,"detuneCents":7,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":2500,"resonance":0.3,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":2.0,"decay":1.5,"sustain":0.7,"release":4.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.6,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.7,"reverbSize":0.9,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"b35613d6061d22f9"})DIDA";
static const char* kPreset_Glass_EP = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Glass EP","category":"Keys","tags":["ep","glass","clean"],"description":"Crystal clear electric piano","oscA":{"waveform":"sine","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"triangle","level":0.4,"detuneCents":0,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":6000,"resonance":0.1,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":1.0,"sustain":0.3,"release":1.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.3,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.2,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"e0933bc5699081c1"})DIDA";
static const char* kPreset_Glo_Alien_Lead = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":8,"glideTime":0.03,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Glo Alien Lead","category":"Lead","tags":["alien","glowing","bright"],"description":"Bright otherworldly lead","oscA":{"waveform":"supersaw","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":4,"unisonDetune":0.3,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.3,"detuneCents":0,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":6000,"resonance":0.4,"drive":0,"envAmount":0.3,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.3,"sustain":0.8,"release":0.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.3,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0.2,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.2,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"6d3c05c35e025ed6"})DIDA";
static const char* kPreset_Hollow_Bell = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"fm2op","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Hollow Bell","category":"Keys","tags":["bell","hollow","ambient"],"description":"Metallic hollow bell tone","oscA":{"waveform":"sine","level":0.6,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.5,"detuneCents":0,"octave":0,"semitone":5,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"BP","cutoff":2000,"resonance":0.4,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":3.0,"sustain":0,"release":4.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.5,"reverbSize":0.8,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"588f90839c2c059a"})DIDA";
static const char* kPreset_Mellow_Tape_Pad = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Mellow Tape Pad","category":"Pad","tags":["tape","mellow","lo-fi"],"description":"Warm tape-saturated pad","oscA":{"waveform":"saw","level":0.5,"detuneCents":5,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"triangle","level":0.4,"detuneCents":-5,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":2500,"resonance":0.15,"drive":0.2,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":1.0,"decay":1.5,"sustain":0.75,"release":3.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.3,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.3,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"0df2529229358770"})DIDA";
static const char* kPreset_Metallic_Pluck = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Metallic Pluck","category":"Pluck","tags":["metallic","bright","sharp"],"description":"Sharp metallic pluck","oscA":{"waveform":"saw","level":0.6,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"square","level":0.3,"detuneCents":0,"octave":1,"semitone":7,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":8000,"resonance":0.4,"drive":0,"envAmount":0.9,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.2,"sustain":0,"release":0.4},"env2":{"attack":0.001,"decay":0.1,"sustain":0,"release":0.15},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"5745cdc60a859c4c"})DIDA";
static const char* kPreset_Pluck_Bass = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Pluck Bass","category":"Bass","tags":["pluck","tight","staccato"],"description":"Short plucked bass sound","oscA":{"waveform":"saw","level":0.8,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":3000,"resonance":0.3,"drive":0,"envAmount":0.8,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.15,"sustain":0,"release":0.1},"env2":{"attack":0.001,"decay":0.1,"sustain":0,"release":0.05},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"0154ccb18b1ae516"})DIDA";
static const char* kPreset_Soft_Pluck = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Soft Pluck","category":"Pluck","tags":["soft","gentle","acoustic"],"description":"Gentle plucked string","oscA":{"waveform":"triangle","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.3,"detuneCents":0,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":5000,"resonance":0.15,"drive":0,"envAmount":0.6,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.4,"sustain":0,"release":0.8},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.2,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"9392a379299bac8d"})DIDA";
static const char* kPreset_Space_Organ = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Space Organ","category":"Keys","tags":["organ","space","ethereal"],"description":"Ethereal space organ","oscA":{"waveform":"sine","level":0.5,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0.4,"detuneCents":0,"octave":1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":6000,"resonance":0.1,"drive":0,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.1,"decay":0.3,"sustain":0.9,"release":1.0},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":5.5,"shape":"sine","sync":false,"depth":0.15},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[{"source":"lfo1","destination":"oscAPitch","amount":0.02,"bipolar":true}],"fxChain":{"chorusMix":0.5,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.5,"reverbSize":0.7,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"bc965d9dca6842a1"})DIDA";
static const char* kPreset_Staccato_Synth_Strings = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Staccato Synth Strings","category":"Strings","tags":["staccato","synth","short"],"description":"Short synth string stabs","oscA":{"waveform":"saw","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":3,"unisonDetune":0.15,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":4000,"resonance":0.2,"drive":0,"envAmount":0.5,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.15,"sustain":0.2,"release":0.2},"env2":{"attack":0.005,"decay":0.1,"sustain":0,"release":0.1},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"7e6420c47b2ab8b9"})DIDA";
static const char* kPreset_Synth_Brass_Stack = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Synth Brass Stack","category":"Brass","tags":["brass","stack","bold"],"description":"Bold layered synth brass","oscA":{"waveform":"saw","level":0.6,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":3,"unisonDetune":0.15,"unisonSpread":0.5},"oscB":{"waveform":"saw","level":0.5,"detuneCents":7,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":3000,"resonance":0.3,"drive":0,"envAmount":0.4,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.03,"decay":0.2,"sustain":0.85,"release":0.3},"env2":{"attack":0.02,"decay":0.15,"sustain":0.5,"release":0.2},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"f7a4cd6eee1a4379"})DIDA";
static const char* kPreset_Tape_Keys = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Tape Keys","category":"Keys","tags":["tape","lo-fi","warm"],"description":"Warm lo-fi keyboard with tape character","oscA":{"waveform":"saw","level":0.5,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"square","level":0.3,"detuneCents":5,"octave":0,"semitone":0,"pulseWidth":0.45,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":3500,"resonance":0.2,"drive":0.15,"envAmount":0,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.01,"decay":0.6,"sustain":0.5,"release":0.8},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.4,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.15,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"72cbf1ef20505968"})DIDA";
static const char* kPreset_Tight_Synth_Pluck = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Tight Synth Pluck","category":"Pluck","tags":["synth","tight","punchy"],"description":"Punchy short synth pluck","oscA":{"waveform":"saw","level":0.8,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"sine","level":0,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":6000,"resonance":0.35,"drive":0,"envAmount":0.85,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.001,"decay":0.1,"sustain":0,"release":0.15},"env2":{"attack":0.001,"decay":0.08,"sustain":0,"release":0.1},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"c3d33f10f30563d1"})DIDA";
static const char* kPreset_Warm_Analog_Bass = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":1,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Warm Analog Bass","category":"Bass","tags":["analog","warm","classic"],"description":"Round analog-style bass","oscA":{"waveform":"saw","level":0.6,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"oscB":{"waveform":"square","level":0.4,"detuneCents":0,"octave":-1,"semitone":0,"pulseWidth":0.4,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":true,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":600,"resonance":0.25,"drive":0.1,"envAmount":0.4,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.005,"decay":0.4,"sustain":0.6,"release":0.3},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"f164068b63373bb8"})DIDA";
static const char* kPreset_Wide_Analog_Pad = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"poly","masterGain":-3,"polyphony":8,"glideTime":0,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Wide Analog Pad","category":"Pad","tags":["analog","wide","warm"],"description":"Classic wide analog pad","oscA":{"waveform":"saw","level":0.5,"detuneCents":8,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":3,"unisonDetune":0.4,"unisonSpread":0.9},"oscB":{"waveform":"square","level":0.3,"detuneCents":-8,"octave":0,"semitone":0,"pulseWidth":0.45,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":2000,"resonance":0.2,"drive":0,"envAmount":0.15,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.8,"decay":1.0,"sustain":0.8,"release":2.5},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.4,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0.4,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"e308c9481bf9c7e1"})DIDA";
static const char* kPreset_Wide_Portamento_Lead = R"DIDA({"presetVersion":"1.0.0","author":"DIDITAGAIN","engineMode":"subtractive","playMode":"mono","masterGain":-3,"polyphony":8,"glideTime":0.15,"uiSkinRef":"default","tuningRef":"12tet-440","signature":"","presetName":"Wide Portamento Lead","category":"Lead","tags":["portamento","wide","smooth"],"description":"Smooth gliding lead with stereo width","oscA":{"waveform":"saw","level":0.7,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":3,"unisonDetune":0.35,"unisonSpread":0.8},"oscB":{"waveform":"sine","level":0,"detuneCents":0,"octave":0,"semitone":0,"pulseWidth":0.5,"unisonVoices":1,"unisonDetune":0.2,"unisonSpread":0.5},"subOsc":{"enabled":false,"level":0.5,"octave":-1},"noise":{"type":"white","level":0},"filter1":{"type":"LP24","cutoff":5000,"resonance":0.3,"drive":0,"envAmount":0.2,"keyTrack":0},"filter2":{"type":"HP12","cutoff":80,"resonance":0,"drive":0,"envAmount":0,"keyTrack":0},"env1":{"attack":0.05,"decay":0.3,"sustain":0.8,"release":0.6},"env2":{"attack":0.01,"decay":0.5,"sustain":0.3,"release":0.5},"env3":{"attack":0.01,"decay":0.8,"sustain":0,"release":0.3},"lfo1":{"rate":1.0,"shape":"sine","sync":false,"depth":0.5},"lfo2":{"rate":0.5,"shape":"triangle","sync":false,"depth":0.5},"modMatrix":[],"fxChain":{"chorusMix":0.4,"chorusRate":1.0,"chorusDepth":0.3,"delayMix":0.15,"delayTime":0.3,"delayFeedback":0.4,"delaySync":false,"reverbMix":0,"reverbSize":0.5,"reverbDamping":0.5,"phaserMix":0,"phaserRate":0.5,"distortionAmount":0,"distortionType":"soft","compressorThreshold":-10,"compressorRatio":4,"eqLow":0,"eqMid":0,"eqHigh":0,"limiterCeiling":-0.3},"macroKnobs":[{"label":"Brightness","value":0.5,"mappings":[]},{"label":"Movement","value":0.5,"mappings":[]},{"label":"Space","value":0.5,"mappings":[]},{"label":"Dirt","value":0,"mappings":[]},{"label":"Attack","value":0.5,"mappings":[]},{"label":"Width","value":0.5,"mappings":[]},{"label":"Tone","value":0.5,"mappings":[]},{"label":"Mix","value":0.5,"mappings":[]}],"checksum":"cce627b59da5796d"})DIDA";
// ---------------------------------------------------------------------------
//  Sampler presets — each one points at a folder under
//      Documents/DIDITAGAIN STUDIO/Samples/<InstrumentName>/
//  Drop one-shots into the matching folder with names like
//  "Brass_C3.wav", "Piano_F#4_v100.wav" etc. (see SAMPLES_README.md).
// ---------------------------------------------------------------------------
#define DIDA_SAMPLER_PRESET(varName, displayName, folder, category, attack, release, reverbMix) \
    static const char* varName = R"DIDA({"presetVersion":1,"presetName":")" displayName \
    R"(","author":"DIDITAGAIN","category":")" category \
    R"(","tags":["sample","multisample",")" folder \
    R"("],"description":"Plays the multisample folder named ')" folder \
    R"('. Drop audio one-shots into Documents/DIDITAGAIN STUDIO/Samples/)" folder \
    R"(/.","sampler":{"instrument":")" folder \
    R"("},"playMode":"poly","polyphony":16,"masterGain":0.0,"glideTime":0.0,)" \
    R"("filter1":{"type":"LP24","cutoff":18000,"resonance":0.0,"drive":0.0,"envAmount":0.0,"keyTrack":0.0},)" \
    R"("env1":{"attack":)" attack R"(,"decay":0.2,"sustain":1.0,"release":)" release R"(},)" \
    R"("env2":{"attack":0.01,"decay":0.3,"sustain":0.0,"release":0.3},)" \
    R"("env3":{"attack":0.01,"decay":0.3,"sustain":0.0,"release":0.3},)" \
    R"("fxChain":{"chorusMix":0.0,"delayMix":0.0,"delayTime":0.3,"delayFeedback":0.35,"reverbMix":)" reverbMix R"(,"reverbSize":0.6,"distortionAmount":0.0}})DIDA";

// Brass family
DIDA_SAMPLER_PRESET(kPreset_Sampled_Brass,         "Sampled Brass",          "Brass",          "Brass",   "0.005", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Trumpet,       "Sampled Trumpet",        "Trumpet",        "Brass",   "0.01",  "0.3",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Trombone,      "Sampled Trombone",       "Trombone",       "Brass",   "0.02",  "0.4",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_FrenchHorn,    "Sampled French Horn",    "FrenchHorn",     "Brass",   "0.03",  "0.5",  "0.22")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Saxophone,     "Sampled Saxophone",      "Saxophone",      "Brass",   "0.01",  "0.35", "0.15")

// Strings family
DIDA_SAMPLER_PRESET(kPreset_Sampled_Strings,       "Sampled Strings",        "Strings",        "Strings", "0.15",  "0.8",  "0.25")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Violin,        "Sampled Violin",         "Violin",         "Strings", "0.05",  "0.5",  "0.2")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Cello,         "Sampled Cello",          "Cello",          "Strings", "0.08",  "0.6",  "0.22")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Pizzicato,     "Sampled Pizzicato",      "Pizzicato",      "Strings", "0.001", "0.3",  "0.18")

// Keys family
DIDA_SAMPLER_PRESET(kPreset_Sampled_Piano,         "Sampled Piano",          "Piano",          "Keys",    "0.001", "0.5",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_GrandPiano,    "Sampled Grand Piano",    "GrandPiano",     "Keys",    "0.001", "0.6",  "0.2")
DIDA_SAMPLER_PRESET(kPreset_Sampled_RhodesEP,      "Sampled Rhodes EP",      "RhodesEP",       "Keys",    "0.001", "0.6",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_WurliEP,       "Sampled Wurli EP",       "WurliEP",        "Keys",    "0.001", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Organ,         "Sampled Organ",          "Organ",          "Keys",    "0.005", "0.2",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Clavinet,      "Sampled Clavinet",       "Clavinet",       "Keys",    "0.001", "0.25", "0.1")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Harpsichord,   "Sampled Harpsichord",    "Harpsichord",    "Keys",    "0.001", "0.3",  "0.12")

// Mallet / tuned percussion
DIDA_SAMPLER_PRESET(kPreset_Sampled_Marimba,       "Sampled Marimba",        "Marimba",        "Mallet",  "0.001", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Vibraphone,    "Sampled Vibraphone",     "Vibraphone",     "Mallet",  "0.001", "1.2",  "0.2")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Xylophone,     "Sampled Xylophone",      "Xylophone",      "Mallet",  "0.001", "0.3",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Glockenspiel,  "Sampled Glockenspiel",   "Glockenspiel",   "Mallet",  "0.001", "1.0",  "0.25")
DIDA_SAMPLER_PRESET(kPreset_Sampled_MusicBox,      "Sampled Music Box",      "MusicBox",       "Mallet",  "0.001", "1.5",  "0.3")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Kalimba,       "Sampled Kalimba",        "Kalimba",        "Mallet",  "0.001", "0.6",  "0.18")

// Plucked / strung
DIDA_SAMPLER_PRESET(kPreset_Sampled_AcousticGtr,   "Sampled Acoustic Guitar","AcousticGuitar", "Guitar",  "0.001", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_ElectricGtr,   "Sampled Electric Guitar","ElectricGuitar", "Guitar",  "0.001", "0.4",  "0.12")
DIDA_SAMPLER_PRESET(kPreset_Sampled_NylonGtr,      "Sampled Nylon Guitar",   "NylonGuitar",    "Guitar",  "0.001", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Bass,          "Sampled Bass",           "Bass",           "Bass",    "0.001", "0.3",  "0.05")
DIDA_SAMPLER_PRESET(kPreset_Sampled_UprightBass,   "Sampled Upright Bass",   "UprightBass",    "Bass",    "0.001", "0.3",  "0.1")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Harp,          "Sampled Harp",           "Harp",           "Strings", "0.001", "1.5",  "0.25")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Sitar,         "Sampled Sitar",          "Sitar",          "World",   "0.001", "0.8",  "0.2")

// Wind
DIDA_SAMPLER_PRESET(kPreset_Sampled_Flute,         "Sampled Flute",          "Flute",          "Wind",    "0.02",  "0.3",  "0.2")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Clarinet,      "Sampled Clarinet",       "Clarinet",       "Wind",    "0.02",  "0.3",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Oboe,          "Sampled Oboe",           "Oboe",           "Wind",    "0.02",  "0.3",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_PanFlute,      "Sampled Pan Flute",      "PanFlute",       "Wind",    "0.02",  "0.4",  "0.25")

// Vocal / choir
DIDA_SAMPLER_PRESET(kPreset_Sampled_Choir,         "Sampled Choir",          "Choir",          "Vocal",   "0.2",   "1.0",  "0.3")
DIDA_SAMPLER_PRESET(kPreset_Sampled_VocalAhh,      "Sampled Vocal Ahh",      "VocalAhh",       "Vocal",   "0.05",  "0.6",  "0.25")
DIDA_SAMPLER_PRESET(kPreset_Sampled_VocalOoh,      "Sampled Vocal Ooh",      "VocalOoh",       "Vocal",   "0.05",  "0.6",  "0.25")

// Percussion / drum kit
DIDA_SAMPLER_PRESET(kPreset_Sampled_DrumKit,       "Sampled Drum Kit",       "DrumKit",        "Drums",   "0.001", "0.2",  "0.05")
DIDA_SAMPLER_PRESET(kPreset_Sampled_808Kit,        "Sampled 808 Kit",        "808Kit",         "Drums",   "0.001", "0.4",  "0.0")
DIDA_SAMPLER_PRESET(kPreset_Sampled_Percussion,    "Sampled Percussion",     "Percussion",     "Drums",   "0.001", "0.3",  "0.1")

// Synth / hybrid sample folders (use these for your own one-shot leads, pads, etc.)
DIDA_SAMPLER_PRESET(kPreset_Sampled_SynthLead,     "Sampled Synth Lead",     "SynthLead",      "Lead",    "0.001", "0.4",  "0.15")
DIDA_SAMPLER_PRESET(kPreset_Sampled_SynthPad,      "Sampled Synth Pad",      "SynthPad",       "Pad",     "0.3",   "1.5",  "0.35")
DIDA_SAMPLER_PRESET(kPreset_Sampled_SynthPluck,    "Sampled Synth Pluck",    "SynthPluck",     "Pluck",   "0.001", "0.3",  "0.18")
DIDA_SAMPLER_PRESET(kPreset_Sampled_SynthBass,     "Sampled Synth Bass",     "SynthBass",      "Bass",    "0.001", "0.25", "0.05")
DIDA_SAMPLER_PRESET(kPreset_Sampled_FX,            "Sampled FX",             "FX",             "FX",      "0.001", "1.0",  "0.3")

const std::vector<EmbeddedPreset>& getAll()
{
    static const std::vector<EmbeddedPreset> presets = {
        { "Chicago Drill Sub", "Bass", kPreset_Chicago_Drill_Sub },
        { "Choir Lead", "Lead", kPreset_Choir_Lead },
        { "Cinematic Hybrid Hit", "FX", kPreset_Cinematic_Hybrid_Hit },
        { "Crystal Pluck", "Pluck", kPreset_Crystal_Pluck },
        { "Dark Air Pad", "Pad", kPreset_Dark_Air_Pad },
        { "Dark FM Bass", "Bass", kPreset_Dark_FM_Bass },
        { "Dark Music Box", "Keys", kPreset_Dark_Music_Box },
        { "Dark Stringer", "Strings", kPreset_Dark_Stringer },
        { "Digital Cry Lead", "Lead", kPreset_Digital_Cry_Lead },
        { "Dirty Reese", "Bass", kPreset_Dirty_Reese },
        { "Dream Bell", "Keys", kPreset_Dream_Bell },
        { "Ethereal Pad", "Pad", kPreset_Ethereal_Pad },
        { "Evil Square Lead", "Lead", kPreset_Evil_Square_Lead },
        { "FM Marimba", "Pluck", kPreset_FM_Marimba },
        { "Frozen Choir", "Pad", kPreset_Frozen_Choir },
        { "Glass EP", "Keys", kPreset_Glass_EP },
        { "Glo Alien Lead", "Lead", kPreset_Glo_Alien_Lead },
        { "Hollow Bell", "Keys", kPreset_Hollow_Bell },
        { "Mellow Tape Pad", "Pad", kPreset_Mellow_Tape_Pad },
        { "Metallic Pluck", "Pluck", kPreset_Metallic_Pluck },
        { "Pluck Bass", "Bass", kPreset_Pluck_Bass },
        { "Soft Pluck", "Pluck", kPreset_Soft_Pluck },
        { "Space Organ", "Keys", kPreset_Space_Organ },
        { "Staccato Synth Strings", "Strings", kPreset_Staccato_Synth_Strings },
        { "Synth Brass Stack", "Brass", kPreset_Synth_Brass_Stack },
        { "Tape Keys", "Keys", kPreset_Tape_Keys },
        { "Tight Synth Pluck", "Pluck", kPreset_Tight_Synth_Pluck },
        { "Warm Analog Bass", "Bass", kPreset_Warm_Analog_Bass },
        { "Wide Analog Pad", "Pad", kPreset_Wide_Analog_Pad },
        { "Wide Portamento Lead", "Lead", kPreset_Wide_Portamento_Lead },
        { "Sampled Brass", "Brass", kPreset_Sampled_Brass },
    };
    return presets;
}

int extractMissing(const juce::File& targetDir)
{
    if (!targetDir.exists()) targetDir.createDirectory();
    int written = 0;
    for (auto& p : getAll())
    {
        auto safe = juce::String(p.name).replaceCharacters(" /\\:*?\"<>|", "__________");
        auto file = targetDir.getChildFile(safe + ".didasynthpreset");
        if (! file.existsAsFile())
        {
            file.replaceWithText(juce::String::fromUTF8(p.json));
            ++written;
        }
    }
    return written;
}

}} // namespace dida::factory
